Repository platers/obsidian-linter, pull requests merged in 2022-06, with the labels that each got.

#213 Compact YAML Remove Inner Empty Lines
  docs/rules.md
  src/rules.ts
Labels: rule suggestion

#215 Add Consistency Rules for Emphasis and Strong
  README.md
  docs/rules.md
  src/rules.ts
  src/utils.ts
Labels: rule suggestion

#222 Add No Bare URLs Rule
  README.md
  docs/rules.md
  manifest.json
  src/main.ts
  src/rules.ts
  versions.json
Labels: rule suggestion

#227 Make Remove Multiple Whitespace Remove Multiple Spaces Around Non-Letters
  src/rules.ts
  src/test.ts
Labels: bug

#230 added "<URL>" to patterns excluded from No Bare URLs
  src/rules.ts
Labels: bug

#231 Fix a Couple of Issues Around Header Increment
  docs/rules.md
  src/rules.ts
  src/test.ts
Labels: bug, documentation, enhancement

#232 Add Two Spaces at the End of Lines with Content Continued on the Next Line
  README.md
  docs/rules.md
  src/rules.ts
  src/utils.ts
Labels: enhancement

#233 Update Notice Logic for Error Handling and When to Display Command Pallet Rule for Lint Folder
  src/main.ts
  src/utils.ts
Labels: enhancement

#237 Escape YAML Where possible
  README.md
  docs/rules.md
  src/main.ts
  src/rules.ts
Labels: documentation, rule suggestion, yaml

#238 Fix Checkboxes Followed by Regular Markdown Link when Removing Whitespace from Link
  src/test.ts
  src/utils.ts
Labels: bug, markdown

#239 Release Prep and Ignoring YAML for 2 Spaces Between Content Continued on the Next Line
  manifest.json
  src/utils.ts
  versions.json
Labels: rule suggestion, markdown

#242 Fix Placeholders' First Character Matching "\b" for Regex
  src/test.ts
  src/utils.ts
Labels: bug
