Repository platers/obsidian-linter, pull requests merged in 2023-11, with the labels that each got.

#937 `No Bare URLs` Should not Include `>` or Chinese Characters
  __tests__/no-bare-urls.test.ts
  src/utils/regex.ts
Labels: bug, markdown

#939 `Blockquote Style`: Handle `>` in Blockquotes So They Are Not Affected
  __tests__/blockquote-style.test.ts
  package-lock.json
  src/rules/blockquote-style.ts
  src/utils/strings.ts
Labels: bug, markdown

#942 Fix Getting First Header Not Handling `#` at End of Markdown Link Display Text
  __tests__/yaml-title.test.ts
  src/utils/regex.ts
Labels: bug, markdown

#940 Add Ability to Run Custom Commands on Folder and Vault Lint
  package-lock.json
  package.json
  src/lang/locale/en.ts
  src/main.ts
  src/ui/modals/lint-confirmation-modal.ts
Labels: enhancement

#946 Update Dependencies
  babel.config.js
  esbuild.config.mjs
  package-lock.json
  package.json
Labels: dependencies

#945 Fix Newline Blockquote Recognition
  __tests__/empty-line-around-blockquotes.test.ts
  src/rules-runner.ts
  src/rules/trailing-spaces.ts
  src/utils/strings.ts
Labels: bug, markdown

#947 Fix: Linter break obsidian save file.
  src/main.ts
Labels: bug, obsidian

#953 Fix Ignored Syntax Getting Included in Tags
  __tests__/move-tags-to-yaml.test.ts
  package-lock.json
  package.json
  src/utils/regex.ts
Labels: bug, obsidian

#955 Add Rule `Add Blank Line After YAML`
  __tests__/add-blank-line-after-yaml.test.ts
  src/lang/locale/en.ts
  src/rules/add-blank-line-after-yaml.ts
Labels: rule suggestion, yaml
